-- //////////// Create Table
create table students(
    student_id number generated by default as identity,
    first_name varchar(20),
    last_name varchar(30),
    email varchar(255) unique
);

create table teachers as select * from students;
drop table teachers;
create table teacher as select first_name, last_name, email from students;



-- //////////// Alter table
/*
	for Update The Structure Table:
		Add, Modify, Drop, Rename and Delete
	"ALTER TABLE table_name action;"
*/
-- Add New Colonne
alter table students add number_module number not null; 
alter table students add brithday Date not null;
alter table students add (number_module number not null,  brithday Date not null);

-- Modify Attribute of Table
alter table students modify (
    -- number_module number null, we can modify to null
	-- email varchar(99) not null This is already null
    first_name varchar(10) not null
);

-- Drop Column Of Table
alter table students drop (number_module, brithday);

-- Rename Column Of Table
alter table students rename column number_module to module_number;

-- Rename Table Name
alter table students rename to learners;



-- //////////// Virtual Column
/*
	is Column that own value calculated automaticlly
	"column_name [data_type] [GENERATED ALWAYS] AS (expression) [VIRTUAL];"

    Some limitations of virtual columns include:
        • Virtual columns are only supported in relational heap tables,
			but not in index-organized, external, object, clustered, or temporary tables.
        • The virtual column cannot be an Oracle-supplied data type, a user-defined type, or a LOB or LONG RAW type.
    The expression in the virtual column has the following restrictions:
        • It cannot reference other virtual columns.
        • It cannot reference regular columns from other tables.
        • It must return a scalar value.
        • It can reference a deterministic user-defined function, but if so, the virtual column cannot be used as a partitioning key column.
*/
create table employees (
    empl_id number not null unique,
    salary number not null,
    bonus number as ((salary * 10) / 100)
);
alter table students add (bonus number as (student_id * 2));




-- //////////// TRUNCATE TABLE && Define and Delete an Unused Column && Comments in table
/*
	TRUNCATE TABLE: Empty Table, it can delete all rows and free the space.
	
	SET UNUSED: 
		--> Please note: once a column is marked unused, you cannot recover this column.
		--> UNUSED means Clomun deleted logically and can be physically removed later.
		-->  ALTER TABLE table DROP UNUSED COLUMNS;

	Comments in Table:
		--> COMMENT Can Add max of 2000 octect
		--> Comment store in Data Dictionary
*/

truncate table students;
alter table employees set unused column bonus; 
comment on table employees is 'this is a comment for employees table';
SELECT * FROM user_tab_comments; -- display the employees comments --> user_tab_comments is vues --> we can find others also



-- //////////// Contraints
/*
	is rules that apply in each column in the table.
	- Not null, unique, PRIMARY KEY (contain not null, unique), FOREIGN KEY, check and REF.
*/
























