-- DDL (Data Defenition Language)
CREATE TABLE student (
	std_id NUMBER,
	std_name Varchar(30),
	std_email Varchar(30),
	std_password Varchar(30)
);

-- ALTER [ADD, Rename, Modify, Drop, Unsed] 

ALTER TABLE STUDENT SET unused COLUMN std_password
ALTER TABLE STUDENT ADD brithday DATE
ALTER TABLE STUDENT ADD (password varchar(255) DEFAULT '');
ALTER TABLE STUDENT MODIFY brithday varchar(20)
ALTER TABLE student DROP (brithday)
ALTER TABLE student RENAME COLUMN std_std TO std_id
UPDATE STUDENT SET brithday = '24-04-1997' WHERE STD_Money = 10

SELECT * FROM student

-- Virtual Column
SELECT * FROM student
UPDATE STUDENT SET std_password = '11111111' WHERE std_password IS NULL 
ALTER TABLE student RENAME COLUMN password TO std_password
ALTER TABLE student ADD (std_bonus NUMBER AS (std_money * 10))

-- Truncate
TRUNCATE TABLE student

-- Constraint in Creating Tables
SELECT * FROM employees;
DROP TABLE employees;
CREATE TABLE employees(
	emp_id0 NUMBER GENERATED ALWAYS AS IDENTITY -- (START WITH 1 INCREMENT BY 1) --> be DEFAULT START WITH we can ignored it
);
ALTER TABLE employees DROP COLUMN emp_id;
ALTER TABLE employees ADD (emp_id NUMBER GENERATED BY DEFAULT AS identity);
ALTER TABLE employees ADD (emp_id NUMBER GENERATED BY DEFAULT ON NULL AS identity);
ALTER TABLE employees ADD (emp_name varchar(20) NOT NULL UNIQUE);
INSERT INTO employees(emp_name) VALUES ('dddd');

-- Primary Key & FOREIGN Key
CREATE TABLE employees(
	emp_id0 NUMBER GENERATED ALWAYS AS IDENTITY, -- PRIMARY KEY,
	CONSTRAINT cp_emps PRIMARY KEY (emp_id0)
);
SELECT * FROM employees;

CREATE TABLE company (
	comp_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	com_name varchar(20) NOT NULL UNIQUE,
	com_type varchar(1) CHECK (com_type IN ('A', 'E')),
	emp_id0 NUMBER,
	CONSTRAINT fg_emp_id FOREIGN KEY (emp_id0) REFERENCES employees(emp_id0)
);

SELECT * FROM company;



