-- Display Table Info
SELECT * FROM user_tables;
-- Display Tables Informations
SELECT * FROM all_tables;
SELECT * FROM dba_tables;
SELECT * FROM DEPARTMENTS;


-- Tables Organization [index and heap]
CREATE TABLE university (
	id NUMBER
) organization heap;

CREATE TABLE university2 (
	id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY
) organization index; -- must be a PRIMARY key

SELECT * FROM user_tables WHERE table_name = 'UNIVERSITY';


-- Tables Organisation [External tables]
-- CREATE DIRECTORY FIRST
CREATE OR REPLACE directory ext_table_test AS '/home/abdellah';
SELECT * FROM ALL_DIRECTORIES WHERE DIRECTORY_NAME = 'EXT_TABLE_TEST';
DROP directory ext_table_test;

CREATE TABLE IMP_DETAILS_COMMANDES  (
   NO_COMMANDE          NUMBER(6)     ,
   REF_PRODUIT          NUMBER(6)     ,
   PRIX_UNITAIRE        NUMBER(8,2)   ,
   QUANTITE             NUMBER(5)     ,
   REMISE               NUMBER(8,2)   ,
   RETOURNE             NUMBER(1)     ,
   ECHANGE              NUMBER(1)     )
ORGANIZATION EXTERNAL 
	( TYPE ORACLE_DATAPUMP DEFAULT 
	DIRECTORY EXT_TABLE_TEST LOCATION ( 'test.dat'));
DROP TABLE IMP_DETAILS_COMMANDES;
SELECT * FROM IMP_DETAILS_COMMANDES;


-- Check Your Current Schema
SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') FROM DUAL;
GRANT CREATE ANY DIRECTORY TO ABDELLAH;
GRANT READ, WRITE ON DIRECTORY ext_table_cmd_det TO ABDELLAH;


-- Temporay Table [Global]
-- table  will be visible in others session but only from your session you access to rows
-- each sessions can see and modify only its data
--  We Should Be Create A Sessiosn First

CREATE GLOBAL TEMPORARY TABLE CART(
	id number
) ON COMMIT DELETE ROWS; -- we ca use "ON COMMIT PRESERVE ROWS" --> DATA will be store IN session


INSERT INTO CART VALUES(1);
SELECT * FROM CART;
COMMIT;
SELECT * FROM CART;



-- Temorary Table [private]
-- since 18c we can create private session [table will visible just in your session]
-- for me i have 12c --> error: unsupported feature with temporary table
CREATE PRIVATE TEMPORARY TABLE mt_temp_table (
	name varchar2(100)
);





