-- Data Manipulation [INSERT, INSERT ALL, UPDATE, DELETE]
INSERT INTO STUDENTS values(4, 'Ahmed');
INSERT ALL 
	INTO students values(5, 'mohamed')
	INTO students values(6, 'mohamed')
	INTO students values(7, 'mohamed')
	INTO students values(8, 'mohamed')
SELECT * FROM dual;


ALTER TABLE STUDENTS ADD (bourse NUMBER);
UPDATE STUDENTS s SET bourse = student_id * 10;
DELETE FROM STUDENTS WHERE student_id = 7;
SELECT * FROM STUDENTS;


-- Data Manipulation [MERGE]
CREATE TABLE souce_table (
	id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
	name varchar(20)
);
CREATE TABLE target_table (
	id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
	name varchar(20)
);

INSERT INTO souce_table VALUES (1, 'Ahmed');
INSERT INTO souce_table VALUES (2, 'Ali');
INSERT INTO souce_table VALUES (3, 'Mohamed');

INSERT INTO target_table VALUES (1, 'Ahmed');
INSERT INTO target_table VALUES (2, 'mohamed');

SELECT * FROM target_table;
SELECT * FROM souce_table;

MERGE INTO target_table t
USING souce_table s
ON (t.id = s.id)
WHEN MATCHED THEN
  UPDATE SET t.name = s.name
  WHERE t.name != s.name
WHEN NOT MATCHED THEN
  INSERT (id, name) VALUES (s.id, s.name);



