SELECT * FROM IMP_CATEGORIES;
SELECT * FROM IMP_CLIENTS;
SELECT * FROM IMP_COMMANDES;
SELECT * FROM IMP_DETAILS_COMMANDES;
SELECT * FROM IMP_EMPLOYES;
SELECT * FROM IMP_FOURNISSEURS;
SELECT * FROM IMP_PRODUITS;
SELECT * FROM IMP_DIM_TEMPS;


SELECT * FROM IMP_CLIENTS;
SELECT * FROM IMP_DETAILS_COMMANDES;
SELECT * FROM IMP_COMMANDES;

-- 1: 
SELECT code_client FROM IMP_CLIENTS;

-- 2: 
SELECT p.nom_produit, 
       f.societe AS fournisseur, 
       p.unites_stock
FROM IMP_PRODUITS p
JOIN IMP_FOURNISSEURS f ON p.no_fournisseur = f.no_fournisseur
WHERE p.unites_stock < (
    SELECT AVG(p2.unites_stock)
    FROM IMP_PRODUITS p2
    WHERE p2.no_fournisseur = p.no_fournisseur
);


-- 3: Remember we can write in external table
SELECT * FROM IMP_CATEGORIES;
INSERT INTO IMP_CATEGORIES(NOM_CATEGORIE, DESCRIPTION) VALUES ('Boissons', 'cafe un text');
INSERT INTO IMP_CATEGORIES(NOM_CATEGORIE, DESCRIPTION) VALUES ('Laitière', 'femme qui fait le traville de lait');

-- 4: 
UPDATE IMP_PRODUITS SET CODE_CATEGORIE = (SELECT CODE_CATEGORIE FROM IMP_CATEGORIES WHERE NOM_CATEGORIE = 'Boissons' )
WHERE REF_PRODUIT IN (2, 24, 34, 35, 38, 39, 67);

-- 5:
DELETE FROM IMP_CATEGORIES WHERE NOM_CATEGORIE = 'Boissons';

-- 6:
SELECT * FROM IMP_CLIENTS WHERE VILLE IN ('Toulouse', 'Strasbourg', 'Nantes', 'Marseille');

-- 7:
SELECT FONCTION, sum(SALAIRE) FROM IMP_EMPLOYES GROUP BY FONCTION;

-- 8:
SELECT NOM_PRODUIT, NO_FOURNISSEUR, CODE_CATEGORIE  FROM IMP_PRODUITS GROUP BY (NOM_PRODUIT, NO_FOURNISSEUR, CODE_CATEGORIE);






