package app.com.manage_student.model;
import jakarta.persistence.*;

@Table(name="student") // this is table in database
@Entity // this is an entity

public class Student {

    // @Column(name="student_id") // this is the column in database
    @Id // --> this is primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // the student_id is generated by default
    @Column()
    private int student_id;
    private String student_name;
    private String student_email;
    private String student_password;

}



