package app.com.manage_student.model;


import jakarta.persistence.*;

@Entity
@Table
public class Student {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "student_id")
    private int student_id; // this is primary key
    @Column(name = "student_name", columnDefinition = "varchar(255) default 'John Snow'")
    private String student_name;
    @Column(name = "student_email", columnDefinition = "varchar(255) default 'j@gmail.com'")
    private String student_email;
    @Column(name = "student_password", columnDefinition = "varchar(255) 'null'")
    private String student_password;

    public Student() {}
    public Student(int student_id, String student_email, String student_name, String student_password) {
        this.student_id = student_id;
        this.student_email = student_email;
        this.student_name = student_name;
        this.student_password= student_password;
    }

    public int getStudent_id() {
        return student_id;
    }

    public void setStudent_id(int student_id) {
        this.student_id = student_id;
    }

    public String getStudent_name() {
        return student_name;
    }

    public void setStudent_name(String student_name) {
        this.student_name = student_name;
    }

    public String getStudent_email() {
        return student_email;
    }

    public void setStudent_email(String student_email) {
        this.student_email = student_email;
    }

    public String getStudent_password() {
        return student_password;
    }

    public void setStudent_password(String student_password) {
        this.student_password = student_password;
    }
}



//@Table(name="student") // this is table in database
//@Entity // this is an entity
//
//public class Student {
//
//    // @Column(name="student_id") // this is the column in database
//    @Id // --> this is primary key
//    @GeneratedValue(strategy = GenerationType.IDENTITY) // the student_id is generated by default
//    @Column(name="student_id")
//    public int student_id;
//    @Column(name="student_name")
//    public String student_name;
//    @Column(name="student_email")
//    public String student_email;
//    @Column(name="student_password")
//    public String student_password;
//
//}